sudo: required
language: node_js
node_js:
  - "8"
addons:
  ssh_known_hosts: kraken.ole.org
  apt:
    packages:
      - docker-ce
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/063276d3941fa8443947
    on_success: always  # options: [always|never|change] default: change
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: never
services:
  - docker
script:
  - source ./.travis/travis_utils.sh
  - build_message under construction ...
deploy:
  - source ./.travis/travis_utils.sh
  - build_message under construction ...